# Generated by Django 6.0.6 on 2026-08-28 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectorium', '0003_lecture_disliked_users_lecture_liked_users'),
        ('library', '0002_initial'),
        ('materials', '0004_delete_comment'),
        ('teachers', '0003_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='добавлена')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='library.book', verbose_name='книга')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='materials.material', verbose_name='материал')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='lectorium.playlist', verbose_name='курс лекций')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='teachers.teacher', verbose_name='преподаватель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
            ],
            options={
                'verbose_name': 'закладка',
                'verbose_name_plural': 'закладки',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('user', 'material'), name='one_bookmark_per_material'), models.UniqueConstraint(fields=('user', 'book'), name='one_bookmark_per_book'), models.UniqueConstraint(fields=('user', 'playlist'), name='one_bookmark_per_playlist'), models.UniqueConstraint(fields=('user', 'teacher'), name='one_bookmark_per_teacher')],
            },
        ),
    ]
