# Generated by Django 6.0.6 on 2026-08-20 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='адрес')),
                ('agent', models.CharField(blank=True, max_length=200, verbose_name='браузер')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='вход')),
                ('seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последний запрос')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='sessions.session', verbose_name='сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сессия',
                'verbose_name_plural': 'сессии',
                'ordering': ['-seen'],
            },
        ),
    ]
