# Generated by Django 6.0.6 on 2026-08-08 11:39

import attachments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to='users/photos', verbose_name='фото'),
        ),
    ]
