# Generated by Django 6.0.6 on 2026-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=140, verbose_name='статус'),
        ),
    ]
