# Generated by Django 6.0.6 on 2026-08-08 12:02

import attachments.storage
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=users.models.photo_upload_to, verbose_name='фото'),
        ),
    ]
