# Generated by Django 6.0.6 on 2026-10-04 12:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_ci', violation_error_message='Человек с такой почтой уже зарегистрирован'),
        ),
    ]
