# Generated by Django 6.0.6 on 2026-08-25 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectorium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=40, verbose_name='рецепт')),
                ('source', models.CharField(max_length=200, verbose_name='сырьё (ключ)')),
                ('status', models.CharField(choices=[('waiting', 'ждёт'), ('baking', 'печётся'), ('done', 'готово'), ('failed', 'не вышло')], db_index=True, default='waiting', max_length=10, verbose_name='состояние')),
                ('prefix', models.CharField(blank=True, max_length=200, verbose_name='папка готового')),
                ('manifest', models.JSONField(blank=True, default=dict, verbose_name='описание готового')),
                ('claimed_by', models.CharField(blank=True, max_length=100, verbose_name='кто взял')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='когда взяли')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='попыток')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='что пошло не так')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('lecture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='lectorium.lecture', verbose_name='лекция')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'очередь выпечки',
                'ordering': ['-created'],
            },
        ),
    ]
