# Generated by Django 6.0.6 on 2026-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_mediajob_tries'),
        ('lectorium', '0003_lecture_disliked_users_lecture_liked_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediajob',
            constraint=models.UniqueConstraint(fields=('source',), name='intake_job_source_once'),
        ),
    ]
