# Generated by Django 6.0.6 on 2026-08-25 20:45

import django.db.models.deletion
import django.utils.timezone
import lectorium.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('teachers', '0003_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'на проверке'), ('approved', 'опубликовано'), ('rejected', 'отклонено')], db_index=True, default='pending', max_length=10, verbose_name='статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='проверено')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='причина отказа')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('synopsis', models.TextField(blank=True, verbose_name='описание')),
                ('year', models.PositiveSmallIntegerField(default=lectorium.models.current_year, verbose_name='год')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='проверил')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlists', to='core.subject', verbose_name='предмет')),
                ('teachers', models.ManyToManyField(blank=True, related_name='playlists', to='teachers.teacher', verbose_name='преподаватели')),
                ('terms', models.ManyToManyField(blank=True, related_name='playlists', to='core.term', verbose_name='семестры')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'плейлист',
                'verbose_name_plural': 'плейлисты',
                'ordering': ['-year', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('prefix', models.CharField(max_length=200, unique=True, verbose_name='папка набора')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='длительность (с)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='добавлена')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectorium.playlist', verbose_name='плейлист')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
                'ordering': ['order', 'id'],
            },
        ),
    ]
