# Generated by Django 6.0.6 on 2026-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, verbose_name='папка набора'),
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(condition=models.Q(('prefix', ''), _negated=True), fields=('prefix',), name='one_lecture_per_folder'),
        ),
    ]
