# Generated by Django 6.0.6 on 2026-08-26 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectorium', '0002_alter_lecture_prefix_lecture_one_lecture_per_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
