# Generated by Django 6.0.6 on 2026-08-09 08:24
# Правлена вручную: обсуждение переехало в приложение `comments`, и ссылка на функцию
# имени файла поехала за ним. На уже применённую миграцию это не влияет — upload_to
# нужен только при сохранении НОВОГО файла, а исторические модели файлов не пишут.

import attachments.storage
import django.utils.timezone
import comments.models
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author', models.BooleanField(default=False, verbose_name='анонимно')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('image', models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=comments.models.comment_image_to, verbose_name='изображение')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'на проверке'), ('approved', 'опубликовано'), ('rejected', 'отклонено')], db_index=True, default='pending', max_length=10, verbose_name='статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='проверено')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='причина отказа')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('synopsis', models.TextField(blank=True, verbose_name='описание')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('hide_uploader', models.BooleanField(default=False, verbose_name='анонимно')),
                ('year', models.PositiveSmallIntegerField(default=materials.models.current_year, verbose_name='год')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
                'ordering': ['-created'],
            },
        ),
    ]
