# Generated by Django 6.0.6 on 2026-08-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='comment',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='materials.comment', verbose_name='ответ на'),
        ),
        migrations.AddField(
            model_name='material',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='проверил'),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.subject', verbose_name='предмет'),
        ),
        migrations.AddField(
            model_name='material',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='materials', to='teachers.teacher', verbose_name='преподаватели'),
        ),
        migrations.AddField(
            model_name='material',
            name='terms',
            field=models.ManyToManyField(blank=True, related_name='materials', to='core.term', verbose_name='семестры'),
        ),
        migrations.AddField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='загрузил'),
        ),
        migrations.AddField(
            model_name='comment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.material', verbose_name='материал'),
        ),
    ]
