# Generated by Django 6.0.6 on 2026-08-08 12:02

import attachments.storage
import materials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_material_approved_material_review_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=materials.models.comment_image_to, verbose_name='изображение'),
        ),
    ]
