# Generated by Django 6.0.6 on 2026-08-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_free_the_comments_name'),
        # Строго после переноса: иначе таблица уедет вместе с данными.
        ('comments', '0002_carry_over_from_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
