# Generated by Django 6.0.6 on 2026-08-26 23:01

import attachments.storage
import comments.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Порядок правлен вручную: сгенерированный ставил создание ПОСЛЕ удаления старой
# модели, то есть данные сносились бы раньше, чем их успели перенести. Правильный
# порядок: создать новое (0001) -> перенести (0002) -> удалить старое.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectorium', '0002_alter_lecture_prefix_lecture_one_lecture_per_folder'),
        ('materials', '0003_free_the_comments_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author', models.BooleanField(default=False, verbose_name='анонимно')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('image', models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=comments.models.comment_image_to, verbose_name='изображение')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('disliked_users', models.ManyToManyField(blank=True, related_name='disliked_comments', to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lectorium.lecture', verbose_name='лекция')),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.material', verbose_name='материал')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='ответ на')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['created'],
            },
        ),
    ]
