# Generated by Django 6.0.6 on 2026-08-10 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'кошелёк',
                'verbose_name_plural': 'кошельки',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('reason', models.CharField(choices=[('manual', 'начисление вручную'), ('wall_reroll', 'смена цвета на Стене')], max_length=30, verbose_name='причина')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='примечание')),
                ('balance_after', models.PositiveIntegerField(verbose_name='баланс после')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='когда')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='economy.wallet', verbose_name='кошелёк')),
            ],
            options={
                'verbose_name': 'операция',
                'verbose_name_plural': 'операции',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['wallet', '-id'], name='economy_bal_wallet__8638a5_idx')],
            },
        ),
    ]
