# Generated by Django 6.0.6 on 2026-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='reason',
            field=models.CharField(choices=[('manual', 'начисление вручную'), ('welcome', 'стартовые'), ('material', 'материалы'), ('book', 'книги'), ('review', 'отзывы о преподавателях'), ('download', 'скачивания твоих файлов'), ('wall', 'пиксели на Стене'), ('moderation', 'проверка чужих работ')], max_length=30, verbose_name='причина'),
        ),
    ]
