# Generated by Django 6.0.6 on 2026-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_alter_balancelog_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancelog',
            name='key',
            field=models.CharField(blank=True, max_length=64, verbose_name='за что'),
        ),
        migrations.AddIndex(
            model_name='balancelog',
            index=models.Index(fields=['wallet', 'reason', 'key'], name='economy_bal_wallet__37d379_idx'),
        ),
    ]
