# Generated by Django 6.0.6 on 2026-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_balancelog_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='reason',
            field=models.CharField(choices=[('manual', 'начисление вручную'), ('welcome', 'стартовые'), ('material', 'материалы'), ('book', 'книги'), ('review', 'отзывы о преподавателях'), ('likes', 'лайки на твоих отзывах и комментариях'), ('download', 'скачивания твоих файлов'), ('wall', 'пиксели на Стене'), ('moderation', 'проверка чужих работ'), ('purchase', 'покупки в магазине')], max_length=30, verbose_name='причина'),
        ),
    ]
