# Generated by Django 6.0.6 on 2026-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_alter_balancelog_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancelog',
            name='balance_after',
            field=models.IntegerField(verbose_name='баланс после'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='баланс'),
        ),
    ]
