# Generated by Django 6.0.6 on 2026-08-20 19:50

import attachments.storage
import cosmetics.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('kind', models.CharField(choices=[('avatar_frame', 'рамка аватара')], db_index=True, default='avatar_frame', max_length=20, verbose_name='вид')),
                ('rarity', models.CharField(choices=[('common', 'обычная'), ('rare', 'редкая'), ('epic', 'эпическая'), ('legendary', 'легендарная'), ('mythical', 'мифическая')], db_index=True, default='common', max_length=20, verbose_name='редкость')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='описание')),
                ('image', models.ImageField(storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='анимация')),
                ('still', models.ImageField(storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='кадр')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='id на старом сайте')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='добавлена')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['kind', 'rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('avatar_frame', 'рамка аватара')], editable=False, max_length=20, verbose_name='вид')),
                ('equipped', models.BooleanField(default=False, verbose_name='надето')),
                ('acquired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='получено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='cosmetics.cosmeticitem', verbose_name='предмет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'вещь',
                'verbose_name_plural': 'инвентарь',
                'ordering': ['-acquired'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='one_copy_per_person'), models.UniqueConstraint(condition=models.Q(('equipped', True)), fields=('user', 'kind'), name='one_equipped_per_slot')],
            },
        ),
    ]
