# Generated by Django 6.0.6 on 2026-08-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmeticitem',
            name='legacy_id',
        ),
        migrations.AddField(
            model_name='cosmeticitem',
            name='source',
            field=models.CharField(blank=True, max_length=120, verbose_name='источник'),
        ),
        migrations.AddConstraint(
            model_name='cosmeticitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('source',), name='one_item_per_source'),
        ),
    ]
