# Generated by Django 6.0.6 on 2026-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_remove_cosmeticitem_legacy_id_cosmeticitem_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticitem',
            name='kind',
            field=models.CharField(choices=[('avatar_frame', 'рамка аватара'), ('profile_header', 'шапка профиля')], db_index=True, default='avatar_frame', max_length=20, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='kind',
            field=models.CharField(choices=[('avatar_frame', 'рамка аватара'), ('profile_header', 'шапка профиля')], editable=False, max_length=20, verbose_name='вид'),
        ),
    ]
