# Generated by Django 6.0.6 on 2026-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_alter_cosmeticitem_kind_alter_useritem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='пусто — по редкости', null=True, verbose_name='своя цена'),
        ),
        migrations.AddField(
            model_name='cosmeticitem',
            name='sold',
            field=models.BooleanField(default=True, verbose_name='продаётся'),
        ),
    ]
