# Generated by Django 6.0.6 on 2026-08-25 02:56

import attachments.storage
import cosmetics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0006_alter_cosmeticitem_kind_alter_useritem_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticitem',
            name='video',
            field=models.FileField(blank=True, storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='видео'),
        ),
        migrations.AlterField(
            model_name='cosmeticitem',
            name='image',
            field=models.ImageField(storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='картинка'),
        ),
    ]
