# Generated by Django 6.0.6 on 2026-08-25 17:05

import attachments.storage
import cosmetics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0007_cosmeticitem_video_alter_cosmeticitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticitem',
            name='image',
            field=models.ImageField(help_text='у анимированной вещи — первый кадр её видео', storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='cosmeticitem',
            name='video',
            field=models.FileField(blank=True, help_text='mp4 по спеке, испечённый снаружи — сайт не конвертирует', storage=attachments.storage.media_storage, upload_to=cosmetics.models.frame_upload_to, verbose_name='видео'),
        ),
    ]
