# Generated by Django 6.0.6 on 2026-08-10 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('width', models.PositiveSmallIntegerField(default=128, verbose_name='ширина')),
                ('height', models.PositiveSmallIntegerField(default=72, verbose_name='высота')),
                ('is_active', models.BooleanField(default=True, verbose_name='текущая')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='открыта')),
                ('closed', models.DateTimeField(blank=True, null=True, verbose_name='закрыта')),
            ],
            options={
                'verbose_name': 'доска',
                'verbose_name_plural': 'доски',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_board')],
            },
        ),
        migrations.CreateModel(
            name='WallProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveSmallIntegerField(verbose_name='цвет')),
                ('charges', models.PositiveSmallIntegerField(default=5, verbose_name='заряды')),
                ('charged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='отсчёт зарядов')),
                ('rerolls', models.PositiveIntegerField(default=0, verbose_name='менял цвет')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='доска закрыта до')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wall', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'участник Стены',
                'verbose_name_plural': 'участники Стены',
            },
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('color', models.PositiveSmallIntegerField(default=0, verbose_name='цвет')),
                ('placed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='когда')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixels', to='wall.board', verbose_name='доска')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixels', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
            ],
            options={
                'verbose_name': 'пиксель',
                'verbose_name_plural': 'пиксели',
                'constraints': [models.UniqueConstraint(fields=('board', 'x', 'y'), name='unique_pixel')],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('color', models.PositiveSmallIntegerField(verbose_name='цвет')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='когда')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='wall.board', verbose_name='доска')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
            ],
            options={
                'verbose_name': 'событие доски',
                'verbose_name_plural': 'события доски',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['board', 'x', 'y', '-id'], name='wall_placem_board_i_26ee39_idx'), models.Index(fields=['board', 'id'], name='wall_placem_board_i_471acb_idx')],
            },
        ),
    ]
