# Generated by Django 6.0.6 on 2026-08-11 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created'], 'permissions': [('moderate_wall', 'Может править Стену')], 'verbose_name': 'доска', 'verbose_name_plural': 'доски'},
        ),
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.PositiveSmallIntegerField()),
                ('y1', models.PositiveSmallIntegerField()),
                ('x2', models.PositiveSmallIntegerField()),
                ('y2', models.PositiveSmallIntegerField()),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='что это')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='когда')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='wall.board', verbose_name='доска')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='закрыл')),
            ],
            options={
                'verbose_name': 'закрытый участок',
                'verbose_name_plural': 'закрытые участки',
                'ordering': ['-id'],
            },
        ),
    ]
