# Generated by Django 6.0.6 on 2026-08-11 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_alter_board_options_protectedarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='height',
            field=models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MaxValueValidator(255)], verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='board',
            name='width',
            field=models.PositiveSmallIntegerField(default=128, validators=[django.core.validators.MaxValueValidator(255)], verbose_name='ширина'),
        ),
    ]
