# Generated by Django 6.0.6 on 2026-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_alter_board_height_alter_board_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallprofile',
            name='charges',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='заряды'),
        ),
    ]
