# Generated by Django 6.0.6 on 2026-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_alter_wallprofile_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallprofile',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wallprofile',
            name='rerolls',
        ),
        migrations.AddField(
            model_name='wallprofile',
            name='painted',
            field=models.PositiveIntegerField(default=0, verbose_name='закрашено клеток'),
        ),
    ]
