# Generated by Django 6.0.6 on 2026-08-09 08:24

import attachments.storage
import django.core.validators
import django.utils.timezone
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_author', models.BooleanField(default=False, verbose_name='анонимно')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
                ('score_knowledge', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='знания')),
                ('score_skill', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='умение преподавать')),
                ('score_communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='общение')),
                ('score_freeloading', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='халявность')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='отчество')),
                ('bio', models.TextField(blank=True, verbose_name='о преподавателе')),
                ('photo', models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=teachers.models.photo_upload_to, verbose_name='фото')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='почта')),
                ('vk_page', models.CharField(blank=True, max_length=50, verbose_name='VK (без https://vk.com/)')),
                ('tg_page', models.CharField(blank=True, max_length=50, verbose_name='TG (без https://t.me/)')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ['surname', 'name'],
            },
        ),
    ]
