# Generated by Django 6.0.6 on 2026-08-20 15:03

import attachments.storage
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=teachers.models.review_image_to, verbose_name='изображение'),
        ),
    ]
