# Generated by Django 6.0.6 on 2026-08-08 12:02

import attachments.storage
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=teachers.models.photo_upload_to, verbose_name='фото'),
        ),
    ]
