# Generated by Django 6.0.6 on 2026-08-02 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dm', 'личный'), ('group', 'групповой'), ('team', 'учебная группа')], default='dm', max_length=10, verbose_name='тип')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='название')),
                ('dm_key', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='core.team', verbose_name='учебная группа')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='администратор')),
                ('muted', models.BooleanField(default=False, verbose_name='без уведомлений')),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='вступил')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chats.chat', verbose_name='чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='участник')),
            ],
            options={
                'verbose_name': 'участник чата',
                'verbose_name_plural': 'участники чатов',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', through='chats.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('edited', models.DateTimeField(blank=True, null=True, verbose_name='изменено')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat', verbose_name='чат')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chats.message', verbose_name='ответ на')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='last_read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chats.message', verbose_name='прочитано до'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chats.message', verbose_name='последнее сообщение'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16, verbose_name='эмодзи')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создана')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chats.message', verbose_name='сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'id'], name='chats_messa_chat_id_e5b40a_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('chat', 'user'), name='unique_chat_member'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='unique_reaction'),
        ),
    ]
