# Generated by Django 6.0.6 on 2026-08-09 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dm', 'личный'), ('group', 'групповой'), ('course', 'курс')], default='dm', max_length=10, verbose_name='тип')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='название')),
                ('admission_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год поступления')),
                ('stage', models.CharField(blank=True, choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], max_length=20, verbose_name='ступень обучения')),
                ('dm_key', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ['-id'],
                'permissions': [('curate_course_chats', 'Может быть куратором чата курса')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('edited', models.DateTimeField(blank=True, null=True, verbose_name='изменено')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='изменение контента')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16, verbose_name='эмодзи')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создана')),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='администратор')),
                ('muted', models.BooleanField(default=False, verbose_name='без уведомлений')),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='вступил')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chats.chat', verbose_name='чат')),
            ],
            options={
                'verbose_name': 'участник чата',
                'verbose_name_plural': 'участники чатов',
            },
        ),
    ]
