# Generated by Django 6.0.6 on 2026-08-02 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id'], 'permissions': [('curate_team_chats', 'Может быть куратором чата учебной группы')], 'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='изменение контента'),
        ),
    ]
