# Generated by Django 6.0.6 on 2026-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_curators_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='изменение контента'),
        ),
    ]
