# Generated by Django 6.0.6 on 2026-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_curators_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='закреплён'),
        ),
    ]
