# Generated by Django 6.0.6 on 2026-08-09 08:24

import attachments.models
import attachments.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('file', models.FileField(storage=attachments.storage.media_storage, upload_to=attachments.models.file_upload_to, verbose_name='файл')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер (байт)')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='скачиваний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='название')),
                ('image', models.ImageField(storage=attachments.storage.media_storage, upload_to=attachments.models.image_upload_to, verbose_name='изображение')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер (байт)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ['order', 'id'],
            },
        ),
    ]
