# Generated by Django 6.0.6 on 2026-08-06 11:09

import attachments.models
import attachments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=attachments.storage.media_storage, upload_to=attachments.models.file_upload_to, verbose_name='файл'),
        ),
    ]
