# Generated by Django 6.0.6 on 2026-09-03 23:18

import attachments.models
import attachments.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
        ('chats', '0003_curators_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chats.message', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='image',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chats.message', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='image',
            name='preview',
            field=models.ImageField(blank=True, null=True, storage=attachments.storage.media_storage, upload_to=attachments.models.preview_upload_to, verbose_name='миниатюра'),
        ),
    ]
