# Generated by Django 6.0.6 on 2026-08-07 17:12

import attachments.models
import attachments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=attachments.storage.media_storage, upload_to=attachments.models.image_upload_to, verbose_name='изображение'),
        ),
    ]
