# Generated by Django 6.0.6 on 2026-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='описание')),
                ('chat_id', models.BigIntegerField(verbose_name='chat ID')),
                ('topic_id', models.BigIntegerField(blank=True, help_text='Только для групп с темами — сообщения уйдут в неё, а не в общий поток.', null=True, verbose_name='ID темы')),
            ],
            options={
                'verbose_name': 'телеграм-чат',
                'verbose_name_plural': 'телеграм-чаты',
            },
        ),
    ]
